### ISSUE TITLE
Added new case failure

### ISSUE THREAD

**Issue by ktavabi** [ktavabi/badbaby#12]
Additional case causing run time `ValueError` during Maxwell filtering.

**Comment by ktavabi** [comment]
@larsoner `maxbad` lists across multiple raw input files _are_ collated into a unique set upstream in mnefun?

**Comment by larsoner** [comment]
@ktavabi can you paste a traceback that you're hitting?

`maxbad` is run-specific, only the `prebad` are shared across all runs

**Comment by ktavabi** [comment]
Seems like differences between `maxbad` lists 1/68 times is odd...

> Traceback (most recent call last):
>   File "/home/ktavabi/Github/badbaby/badbaby/processing/run_mnefun.py", line 101, in <module>
>     mnefun.do_processing(
>   File "/home/ktavabi/Github/mnefun/mnefun/_mnefun.py", line 533, in do_processing
>     outs[ii] = func(p, subjects, run_indices)
>   File "/home/ktavabi/Github/mnefun/mnefun/_sss.py", line 54, in run_sss
>     run_sss_locally(p, subjects, run_indices)
>   File "/home/ktavabi/Github/mnefun/mnefun/_sss.py", line 502, in run_sss_locally
>     raw_sss = maxwell_filter(
>   File "<decorator-gen-410>", line 24, in maxwell_filter
>   File "/home/ktavabi/anaconda3/envs/obiwan/lib/python3.8/site-packages/mne/preprocessing/maxwell.py", line 214, in maxwell_filter
>     params = _prep_maxwell_filter(
>   File "<decorator-gen-411>", line 24, in _prep_maxwell_filter
>   File "/home/ktavabi/anaconda3/envs/obiwan/lib/python3.8/site-packages/mne/preprocessing/maxwell.py", line 301, in _prep_maxwell_filter
>     raise ValueError('%s channel names (length %d) do not match '
> ValueError: extended_proj[0] channel names (length 299) do not match the good MEG channel names (length 297):
> MEG0521, MEG1831

**Comment by larsoner** [comment]
Are you on latest MNE-Python `main`? This should have been fixed back in December I think:

https://github.com/mne-tools/mne-python/pull/8675

**Comment by ktavabi** [comment]
> Are you on latest MNE-Python `main`? This should have been fixed back in December I think:
> 
> [mne-tools/mne-python#8675](https://github.com/mne-tools/mne-python/pull/8675)

I'm up to date with main.

**Comment by larsoner** [comment]
I don't think you're running on latest `main` since line 301 [is blank](https://github.com/mne-tools/mne-python/blob/main/mne/preprocessing/maxwell.py#L301
) in `main` but it's the error line in your traceback. The [actual error message](https://github.com/mne-tools/mne-python/blob/main/mne/preprocessing/maxwell.py#L293-L295) should be:

> '%s channel names were missing some good MEG channel names:\n%s'

But yours matches [what it was before that PR](https://github.com/mne-tools/mne-python/pull/8675/files#diff-d8d8cf775640b2e7d21bb0f747a79c7d1dbd11af1fde3a9ced1587c158aa2918L301-L302). Maybe some IDE misconfiguration / not using the correct conda env?

**Comment by ktavabi** [comment]
Had to reset `.git`
Now 925b is throwing a ValueError #13
